Per Nick's suggestion, use reflection instead of text parsing. Results now look like this:
Error: class pwiz.Skyline.EditUI.EditLinkedPeptidesDlg illegally inherits directly from Form instead of FormEx. Using FormEx ensures proper interaction with automated tests, small molecule interface operation, and other enhancements. If this really is intentional, add "typeof(EditLinkedPeptidesDlg)" to the variable "acceptableDirectUsesOfFormClass" in method "FindIllegalForms" in CodeInspectionTest.cs

Error: class pwiz.Skyline.EditUI.SynchronizedIntegrationDlg illegally inherits directly from Form instead of FormEx. Using FormEx ensures proper interaction with automated tests, small molecule interface operation, and other enhancements. If this really is intentional, add "typeof(SynchronizedIntegrationDlg)" to the variable "acceptableDirectUsesOfFormClass" in method "FindIllegalForms" in CodeInspectionTest.cs