We currently warn about tests that don't inherit from AbstractUnitTest, making it a code inspection error now since it's apparent that a warning doesn't have much weight.
So if, for example, pwiz.SkylineTest.ProtocolBuffers.LegacyProtocolBufferFormatsTest still did not have a base class AbstractUnitTest, you'd see this from our static code inspection test:

Error: test class pwiz.SkylineTest.ProtocolBuffers.LegacyProtocolBufferFormatsTest does not inherit from AbstractUnitTest. Using AbstractUnitTest ensures proper interaction with Skyline's custom automated test system.