Add a WaitForDocumentChange to try to prevent an unsettled .skyd file causing trouble on test exit:
System.IO.IOException: The process cannot access the file 'CE_Vantage_15mTorr_scheduled_mini.skyd' because it is being used by another process.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at pwiz.SkylineTestUtil.TestFilesDir.<>c__DisplayClass26_0.<Dispose>b__1() in Z:\pwiz\pwiz_tools\Skyline\TestUtil\TestFilesDir.cs:line 232
   at pwiz.Skyline.Util.Helpers.TryTwice(Action action, Int32 loopCount, Int32 milliseconds, String hint) in Z:\pwiz\pwiz_tools\Skyline\Util\Util.cs:line 1891
   at pwiz.SkylineTestUtil.TestFilesDir.Dispose() in Z:\pwiz\pwiz_tools\Skyline\TestUtil\TestFilesDir.cs:line 232
   at pwiz.SkylineTestUtil.AbstractFunctionalTest.RunFunctionalTest(String defaultUiMode) in Z:\pwiz\pwiz_tools\Skyline\TestUtil\TestFunctional.cs:line 1320